pipeline{
    agent any
    stages{
        stage('Build Artifact'){
            steps {
                echo 'Building Artifact'
                sh 'mvn clean package -DskipTests'
            }
        }

        stage('Build and Deploy to ECR'){
            steps{
                withCredentials([string(credentialsID: 'ecr-url', variable: 'ECR_URL')]){
                    sh 'aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin $ECR_URL'
                    sh 'docker build -t bank-ms'
                    sh 'docker tag bank:latest $ECR_URL/bank:latest'
                    sh 'docker push $ECR_URL/bank:latest'
                }
            }
        }

        stage('Cleaning'){
            steps{
                sh 'docker image prune -a'
            }
        }
    }
}