version: "3"
services:
  aline-underwriter:
    image: ${AWS_ACCOUNT_NUMBER}.dkr.ecr.us-east-1.amazonaws.com/aline-underwriter-tk:latest
    env_file:
      - .env
    ports:
      - ${UNDERWRITER_PORT}:${UNDERWRITER_PORT}
    deploy:
      resources:
        limits:
          cpus: '.5'
          memory: 2000M
      x-aws-autoscaling:
        min: 1
        max: 5
        cpu: 80
  aline-transaction:
    image: ${AWS_ACCOUNT_NUMBER}.dkr.ecr.us-east-1.amazonaws.com/aline-transaction-tk:latest
    env_file:
      - .env
    ports:
      - ${TRANSACTION_PORT}:${TRANSACTION_PORT}
    deploy:
      resources:
        limits:
          cpus: '.5'
          memory: 2000M
      x-aws-autoscaling:
        min: 1
        max: 5
        cpu: 80

  aline-bank:
    image: ${AWS_ACCOUNT_NUMBER}.dkr.ecr.us-east-1.amazonaws.com/aline-bank-tk:latest
    env_file:
      - .env
    ports:
      - ${BANK_PORT}:${BANK_PORT}
    deploy:
      resources:
        limits:
          cpus: '.5'
          memory: 2000M
      x-aws-autoscaling:
        min: 1
        max: 5
        cpu: 80

  aline-user:
    image: ${AWS_ACCOUNT_NUMBER}.dkr.ecr.us-east-1.amazonaws.com/aline-user-tk:latest
    env_file:
      - .env
    ports:
      - ${USER_PORT}:${USER_PORT}
    deploy:
      resources:
        limits:
          cpus: '.5'
          memory: 2000M
      x-aws-autoscaling:
        min: 1
        max: 5
        cpu: 80

networks:
  default:
      name: db-tk_default