pipeline{
  agent any
  stages{
    stage('Pull Environment Variables') {
      steps{
        withAWS(credentials:"AWS-TK") {
          sh 'aws s3 cp s3://fs-aline-tk/sql-secret.yaml ./kubernetes'
        }
      }
    }

    stage('Attach to Cluster') {
        steps {
            dir('kubernetes') {
                sh 'aws eks update-kubeconfig --region us-west-1 --name aline-tk'
            }
        }
        
    }

    stage('Update Cluster') {
        steps {
            dir('kubernetes') {
                sh 'kubectl apply -f .'
            }
        }
        
    }

    stage('Log Deployments') {
        steps {
            dir('kubernetes') {
                sh 'kubectl get deployments'
            }
        } 
    }
  }
}