pipeline{
  agent any
  stages{
    stage('Pull Environment Variables') {
      steps{
        withAWS(credentials:"AWS-TK") {
          sh 'aws s3 cp s3://fs-aline-tk/sql-secret.yaml ./kubernetes'
        }
      }
    }

    stage('Attach to Cluster') {
        dir('kubernetes') {
            sh 'aws eks update-kubeconfig --region us-west-1 --name aline-tk'
        }
    }

    stage('Update Cluster') {
        dir('kubernetes') {
            sh 'kubectl apply -f .'
        }
    }
  }
}